export const API_END_POINTS = {
  SKILLS: '/',
  SKILL: '/:id',
  SKILL_STATUS: '/skill-status',
  REQUESTED_SKILLS: '/requested',
  APPLICATION_STATUS: '/applications-status',
  APPLICATIONS: '/',
  APPLICATION: '/:id',
  COMPANY_DATA: '/:id',
  GET_RESUMES: '/:id/resumes',
  INTERVIEWS: '/',
  UPDATE_STATUS: '/:id/status',
  INTERVIEW: '/:id',
  INTERVIEW_RESULT: '/:id/result',
  INTERVIEWS_STATUS: '/interviews-status',
};
