export const API_END_POINTS = {
  SKILLS: '/',
  SKILL: '/:skillId',
  SKILL_STATUS: '/skill-status',
  REQUESTED_SKILLS: '/requested',
  APPLICATION_STATUS: '/applications-status/:jobId',
  APPLICATIONS: '/',
  APPLICATION: '/:applicationId',
  COMPANY_DATA: '/:companyId',
  GET_RESUMES: '/:resumeId/resumes',
  INTERVIEWS: '/',
  UPDATE_STATUS: '/:interviewId/status',
  INTERVIEW: '/:interviewId',
  CONFIRM_INTERVIEW: '/:interviewId/confirm',
  INTERVIEW_RESULT: '/:interviewId/result',
  INTERVIEWS_STATUS: '/interviews-status',
  RESCHEDULE_REQUEST: '/:interviewId/request-reschedule',
  GET_NOT_READ_COUNT: '/not-read-count',
  NOTIFICATIONS: '/',
  NOTIFICATION: '/:notificationId',
  COMPANIES: '/',
  JOB: '/:jobId',
  JOBS: '/',
  PROFILE: '/profile',
  UPDATE_PROFILE: '/profile/fields',
  PROFILE_IMAGE: '/profile/image',
  ABOUT: '/profile/about',
  PROFILE_SKILLS: '/profile/skills/:skillId',
  EXPERIENCES: '/profile/experience',
  EXPERIENCE: '/profile/experience/experienceId',
  EDUCATIONS: '/profile/education',
  EDUCATION: '/profile/education/:eduId',
  RESUMES: '/profile/resume',
  RESUME: '/profile/resume/:resumeId',
  HOME: '/home',
  LOGO: '/logo',
  PROFILE_LOGO: '/profile/logo',
  DOCUMENT: '/profle/document',
  SAVED_JOBS: '/saved',
  REPORT_JOB: '/:jobId/reports',
  SAVE_JOB: '/:jobId/save',
  UNSAVE_JOB: '/:jobId/unsave',
  JOB_APPLICATIONS:'/:jobId/applications'
};

export const AUTH_END_POINTS = {
  REGISTER: '/register',
  OTP: '/otp',
  RESEND_OTP: '/resend-otp',
  LOGIN: '/login',
  REFRESH_TOKEN: '/refresh-token',
  LOGOUT: '/logout',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_GOOGOLE_LOGIN: '/admin/google',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  CHANGE_PASSWORD: '/changePassword',
  GOOGLE_LOGIN: '/google',
};
