export const API_ENDPOINTS = {
  JOB: '/jobs',
  JOB_DETAILS: (id: string) => `/jobs/${id}`,
  ALL_SKILLS: '/skills',
  REQUESTED_SKILLS: '/skills/requested',
  SKILLS_STATUS: '/skills/skill-status',
  SKILL: (id: string) => `/skills/${id}`,

  APPLY_JOB: (id: string) => `/applications/${id}`,
  CANDIDATE_APPLICATON_STATUS: (jobId: string) =>
    `/applications/applications-status/${jobId}`,
  APPLICATIONS: '/applications',
  JOB_APPLICATIONS: (jobId: string) => `/jobs/${jobId}/applications`,
  APPLICATION: (id: string) => `/applications/${id}`,
  COMPANY_DATA: (id: string) => `/company/${id}`,
  COMPANY_LOGO: '/company/logo',
  COMPANY_DOCUMENT: '/company/profle/document',
  COMPANY: '/company',
  LOGO: '/company/profile/logo',
  COMPANY_PROFILE: '/company/profile',
  COMPANY_FIELDS: '/company/profile/fields',

  INTERVIEWS: '/interviews',
  INTERVIEWS_STATUS: '/interviews/interviews-status',
  INTERVIEW_STATUS: (id: string) => `/interviews/${id}/status`,
  INTERVIEW: (id: string) => `/interviews/${id}`,
  UPDATE_RESULT: (id: string) => `/interviews/${id}/result`,
  CONFIRM_INTERVIEW: (id: string) => `/interviews/${id}/confirm`,
  RESCHEDULE_REQUEST: (id: string) => `/interviews/${id}/request-reschedule`,
  GENERATE_MEETLINK:'/interviews/meetlink',
  GET_MEET_INFO:(meetId:string)=>`/interviews/meetings/${meetId}`,

  NOTIFICATIONS: `/notifications`,
  NOTIFICATIONS_COUNT: `/notifications/not-read-count`,
  NOTIFICATION: (id: string) => `/notifications/${id}`,
  CHATROOMS: '/chatrooms',
  MESSAGES: (chatroomId: string) => `/chatrooms/${chatroomId}/messages`,
  UNREAD_MESSAGE_COUNT: '/messages/unread-count',
  ADMIN_DASHBOARD: {
    STATUSCARD: '/admin/dashboard/cards',
    COMPANY_JOB_CHARTDATA: '/admin/dashboard/company-job-chartdata',
    JOBCOUNT_BY_INDUSTRY: '/admin/dashboard/industry-jobCount',
    USER_DISTRIBUTION: '/admin/dashboard/user-distribution',
    APP_DATA: '/admin/dashboard/application-distribution',
    INTERVIEW_DATA: '/admin/dashboard/interview-data',
    PENDING_COMPANIES: '/admin/dashboard/pending-companies',
    REPORTED_JOBS: '/admin/dashboard/reported-jobs',
  },
  CANDIDATE_DASHBOARD: {
    STATUSCARD: '/candidate/dashboard/cards',
    PROFILE_DATA: '/candidate/dashboard/profile-data',
    APP_DATA: '/candidate/dashboard/application-details',
    RECOMENTED_JOBS: '/candidate/dashboard/recomented-jobs',
    UPCOMING_INTERVIEW: '/candidate/dashboard/upcoming-intrview',
  },
  COMPANY_DASHBOARD:{
   STATUSCARD:'/company/dashboard/status-data',
   APPDATA:'/company/dashboard/applications-data',
   JOB_DATA:'/company/dashboard/jobs-data',
   INTERVIEW_DATA:'/company/dashboard/interview-data',
   RECENT_ACTIVITIES:'/company/dashboard/recent_activities',
   PENDING_ACTION:'/company/dashboard/pending-actions',
  }
};
