import { createContext } from 'react';

export const THEME_TOKENS = {
  light: {
    pageBg: 'bg-slate-50',
    pageText: 'text-slate-900',
    navBg: 'bg-white',
    navBorder: 'border-slate-100',
    navMuted: 'text-slate-500',
    navActive: 'text-purple-600',
    navIconBg: 'hover:bg-slate-100',
    navAvatarBg: 'bg-purple-50 border border-purple-100 text-purple-600',
    heroGradient: 'bg-gradient-to-b from-purple-50 via-white to-white',
    blobA: 'bg-purple-100',
    blobB: 'bg-violet-100',
    heading: 'text-slate-900',
    searchBarBg: 'bg-fuchsia-100',
    subheading: 'text-slate-500',
    surface: 'bg-white',
    surfaceBorder: 'border-slate-200',
    inputFocus: 'focus-within:bg-purple-50',
    inputText: 'text-slate-700',
    placeholder: 'placeholder:text-slate-400',
    dividerV: 'bg-slate-200',
    dividerH: 'bg-white rounded-full',
    iconMuted: 'text-slate-400',
    cardBg: 'bg-white',
    cardBorder: 'border-slate-200',
    cardHoverBorder: 'hover:border-purple-200',
    cardTitle: 'text-slate-900',
    cardTitleHover: 'group-hover:text-purple-700',
    companyName: 'text-slate-700',
    verifiedText: 'text-slate-400',
    metaBadgeBg: 'bg-purple-50',
    metaBadgeText: 'text-fuchsia-700',
    metaBadgeBorder: 'border-fuchsia-100',
    skillChipBg: 'bg-fuchsia-50',
    skillChipText: 'text-fuchsia-600',
    skillChipBorder: 'border-fuchsia-200',
    secondaryButton: 'bg-white text-purple-700 border border-purple-200',
    salaryText: 'text-slate-800',
    footerText: 'text-slate-500',
    dropdownBg: 'bg-white',
    dropdownBorder: 'border-slate-200',
    dropdownHover: 'hover:bg-purple-50',
    filterBg: 'bg-white',
    filterText: 'text-slate-600',
    filterBorder: 'border-slate-200',
    filterHover: 'hover:border-purple-200 hover:text-purple-700',
    filterActiveBg: 'bg-purple-50',
    filterActiveText: 'text-purple-700',
    filterActiveBorder: 'border-purple-200',
    dashedBorder: 'border-slate-300',
    chipBg: 'bg-purple-50',
    chipText: 'text-purple-700',
    chipBorder: 'border-purple-100',
    resultsMuted: 'text-slate-500',
    resultsStrong: 'text-slate-800',
    sortHover: 'hover:bg-slate-50',
    skeletonBg: 'bg-slate-100',
    emptyIconBg: 'bg-purple-50',
    emptyIconBorder: 'border-purple-100',
    emptyIconText: 'text-purple-500',
    errorIconBg: 'bg-rose-50',
    errorIconBorder: 'border-rose-100',
    errorIconText: 'text-rose-500',
    warnText: 'text-amber-600',
    paginationText: 'text-slate-500',
    paginationHover: 'hover:bg-purple-50',
    toastBg: 'bg-slate-900',
    toastText: 'text-white',
    overlay: 'bg-slate-900',
    appliedBg: 'bg-green-50',
    appliedText: 'text-green-700',
    appliedBorder: 'border-green-200',

    vacancyBg: 'bg-green-50',
    vacancyText: 'text-green-700',
    vacancyBorder: 'border-green-200',

    deadlineBg: 'bg-orange-50',
    deadlineText: 'text-orange-800',
    deadlineDate: 'text-orange-600',
    deadlineBorder: 'border-orange-200',

    viewHover: 'hover:bg-fuchsia-100',
    primaryButton: 'bg-gradient-to-r from-fuchsia-600 to-purple-600 text-white',
    primaryButtonHover: 'hover:from-fuchsia-500 hover:to-purple-500',
 heroAccent: "bg-gradient-to-br from-fuchsia-50 via-purple-50 to-white",
    heroGlow: "bg-fuchsia-300/30",
    secondaryButtonHover: 'hover:bg-purple-50',
     statIconBg: "bg-purple-100", statIconText: "text-purple-600",
    sectionIconBg: "bg-fuchsia-100", sectionIconText: "text-fuchsia-600",
  },
  dark: {
    pageBg: 'bg-slate-950',
    pageText: 'text-slate-100',
    navBg: 'bg-slate-900',
    navBorder: 'border-slate-800',
    navMuted: 'text-slate-400',
    navActive: 'text-purple-400',
    navIconBg: 'hover:bg-slate-800',
    navAvatarBg: 'bg-purple-950 border border-purple-800 text-purple-300',
    heroGradient: 'bg-gradient-to-b from-slate-900 via-slate-950 to-slate-950',

    blobA: 'bg-purple-950',
    blobB: 'bg-violet-950',
    heading: 'text-white',
    searchBarBg: 'bg-slate-700',
    subheading: 'text-slate-400',
    surface: 'bg-slate-900',
    surfaceBorder: 'border-slate-800',
    inputFocus: 'focus-within:bg-slate-800',
    inputText: 'text-slate-100',
    placeholder: 'placeholder:text-slate-500',
    dividerV: 'bg-slate-800',
    dividerH: 'bg-slate-800',
    iconMuted: 'text-slate-500',
    cardBg: 'bg-slate-900',
    cardBorder: 'border-slate-800',
    cardHoverBorder: 'hover:border-purple-700',
    cardTitle: 'text-white',
    cardTitleHover: 'group-hover:text-purple-400',
    companyName: 'text-slate-300',
    verifiedText: 'text-slate-500',
    metaBadgeBg: 'bg-purple-950',
    metaBadgeText: 'text-purple-300',
    metaBadgeBorder: 'border-purple-900',
    skillChipBg: 'bg-slate-800',
    skillChipText: 'text-slate-300',
    skillChipBorder: 'border-slate-700',
    salaryText: 'text-slate-100',
    footerText: 'text-slate-400',
    dropdownBg: 'bg-slate-900',
    dropdownBorder: 'border-slate-800',
    dropdownHover: 'hover:bg-slate-800',
    filterBg: 'bg-slate-900',
    filterText: 'text-slate-300',
    filterBorder: 'border-slate-800',
    filterHover: 'hover:border-purple-700 hover:text-purple-300',
    filterActiveBg: 'bg-purple-950',
    filterActiveText: 'text-purple-300',
    filterActiveBorder: 'border-purple-800',
    dashedBorder: 'border-slate-700',
    chipBg: 'bg-purple-950',
    chipText: 'text-purple-300',
    chipBorder: 'border-purple-900',
    resultsMuted: 'text-slate-400',
    resultsStrong: 'text-slate-100',
    sortHover: 'hover:bg-slate-800',
    skeletonBg: 'bg-slate-800',
    emptyIconBg: 'bg-purple-950',
    emptyIconBorder: 'border-purple-900',
    emptyIconText: 'text-purple-400',
    errorIconBg: 'bg-rose-950',
    errorIconBorder: 'border-rose-900',
    errorIconText: 'text-rose-400',
    warnText: 'text-amber-400',
    paginationText: 'text-slate-400',
    paginationHover: 'hover:bg-slate-800',
    toastBg: 'bg-slate-100',
    toastText: 'text-slate-900',
    overlay: 'bg-black',
heroAccent: "bg-gradient-to-br from-purple-950/40 via-slate-950 to-slate-950",
    heroGlow: "bg-fuchsia-500/10",
     statIconBg: "bg-purple-500/10", statIconText: "text-purple-300",
    sectionIconBg: "bg-fuchsia-500/10", sectionIconText: "text-fuchsia",
    appliedBg: 'bg-green-950',
    appliedText: 'text-green-300',
    appliedBorder: 'border-green-900',

    vacancyBg: 'bg-green-950',
    vacancyText: 'text-green-300',
    vacancyBorder: 'border-green-900',
    secondaryButton: 'bg-slate-900 text-purple-200 border border-slate-700',
    deadlineBg: 'bg-orange-950',
    deadlineText: 'text-orange-300',
    deadlineDate: 'text-orange-400',
    deadlineBorder: 'border-orange-900',
    secondaryButtonHover: 'hover:bg-slate-800',
    primaryButton: 'bg-gradient-to-r from-fuchsia-500 to-purple-500 text-white',
    primaryButtonHover: 'hover:from-fuchsia-400 hover:to-purple-400',
    viewHover: 'hover:bg-purple-950',
  },
};
import { useContext, useState, type ReactNode } from 'react';

type ThemeMode = 'light' | 'dark';

type ThemeContextType = {
  mode: ThemeMode;
  t: typeof THEME_TOKENS.light;
  toggle: () => void;
};

const ThemeContext = createContext<ThemeContextType>({
  mode: 'light',
  t: THEME_TOKENS.light,
  toggle: () => {},
});

export function ThemeContextProvider({ children }: { children: ReactNode }) {
  const [mode, setMode] = useState<ThemeMode>('light');

  const toggle = () => {
    setMode((prev) => (prev === 'light' ? 'dark' : 'light'));
  };

  const t = THEME_TOKENS[mode];

  return (
    <ThemeContext.Provider value={{ mode, t, toggle }}>
      {children}
    </ThemeContext.Provider>
  );
}

export const useTheme = () => useContext(ThemeContext);
